analyzer:
  exclude:
    - "build/**"
    - "lib/generated/*"
    - "lib/icons/*"
    - "**/*.freezed.dart"
    - "**/*g.dart"
    - "*.g.dart"
    - "lib/core/injection/injection.config.dart"

  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    camel_case_types: true
    #    avoid_print: true
    hash_and_equals: true
    always_specify_types: true
    avoid_type_to_string: true
    always_use_package_imports: true
    empty_statements: false
    omit_local_variable_types: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_paramters: true